### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by patricksan** [JavaOpenCVBook/code#1]
Hi,

I tried to execute the chapter1 code it didn't work. The repository you defined in the pom.xml doesn't exist anymore.

Did you find a better solution to have opencv via maven?

**Comment by dannyxyz22** [comment]
Hi Patrick, how are you?

They are working, I have just tried them. The repository does exist. Have you issued the command: "mvn package" to the chapter1 project directory? What is the error you are getting?

Thank you for the feedback,
Daniel

**Comment by patricksan** [comment]
Hi @dannyxyz22,
I just tested at home and it worked.

I got problems with the repository at my company. 
Thanks
