### ISSUE TITLE
opencvjar-runtime v3.0.0 for MacOS does not exist

### ISSUE THREAD

**Issue by hkarakose** [JavaOpenCVBook/code#5]
Hi
I tried to fetch opencvjar-runtime v3.0.0 for MacOS but it doesn't exist in github repo.

```
<dependency>
        <groupId>org.javaopencvbook</groupId>
        <artifactId>opencvjar-runtime</artifactId>
        <version>3.0.0</version>
        <classifier>natives-mac-x86_64</classifier>
    </dependency>
```

**Comment by dannyxyz22** [comment]
Just wondering, can you help me out here? 
I've got no MacOS handy. If you compile it from the source, you'll have it. If you can share with me, I'll upload here so others can use.
Thanks in advance.

**Comment by hkarakose** [comment]
I published a Turkish article to prepare this dependency: http://www.kodfarki.com/2017/06/08/macos-java-opencv-kurulumu/

For those who don't know Turkish, just copy/paste following maven configuration into pom.xml:

```
<dependencies>
   <dependency>
      <groupId>opencv</groupId>
      <artifactId>opencv</artifactId>
      <version>3.2.0</version>
   </dependency>

   <dependency>
      <groupId>opencv</groupId>
      <artifactId>opencvjava-runtime</artifactId>
      <classifier>natives-osx</classifier>
      <version>3.2.0</version>
   </dependency>
   ...
</dependencies>

<repositories>
   <repository>
      <id>kodfarki</id>
      <url>https://raw.githubusercontent.com/kodfarki/repository/master/</url>
   </repository>
</repositories>
```

The example project can be cloned from https://github.com/kodfarki/opencv-example

**Comment by dannyxyz22** [comment]
That's very nice of yours.

Thanks for sharing.
