### ISSUE TITLE
Issue with opencvjar-runtime

### ISSUE THREAD

**Issue by widgetech** [JavaOpenCVBook/code#7]
Morning

Working through your book and not able to get the first program to package via maven. Receiving the below error. Attached is the POM I am using. I am not able find a typo with what you have in the book. I also tried performing the mvn package command on the source code for the book, but getting the same error.

I am using Maven 3.5.4
Also tried Maven 3.3.9
Running from command line and from IntelliJ

Thoughts?

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project my-opencv-app: Could not resolve dependencies for project com.widgetech.app:my-opencv-app:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.javaopencvbook:opencvjar-runtime:jar:natives-windows-x86_64:3.0.0: Failed to read artifact descriptor for org.javaopencvbook:opencvjar-runtime:jar:natives-windows-x86_64:3.0.0: Could not transfer artifact org.javaopencvbook:opencvjar-runtime:pom:3.0.0 from/to widget-snapshots (http://localhost:8081/nexus/content/repositories/snapshots): Connect to localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect -> [Help 1]
[ERROR]
[pom.txt](https://github.com/JavaOpenCVBook/code/files/2153542/pom.txt)

**Comment by widgetech** [comment]
Found an issue with my Maven settings.xml. That has been corrected and mvn package runs without an issue.

**Comment by dannyxyz22** [comment]
Just saw your message today.
I'm glad you've been able to solve it :)
Kind regards,
Daniel
